replicaCount: 1

# Dependencies - CSI driver installed separately
secretStore:
  enabled: false

postgresql:
  enabled: false
  auth:
    username: app_user
    password: app_password
    database: app_database

# CSI Secrets Store Driver - installed separately
secrets-store-csi-driver:
  enabled: false

# Database configuration
database:
  host: "postgres-postgresql"
  port: "5432"
  name: "app_database"

# AWS configuration
aws:
  accountId: "" # Will be set by pipeline
  region: us-east-1

# Secret management (single source of truth)
secrets:
  # AWS Secrets Manager configuration
  awsSecretName: "myapp/db-credentials-v2"
  # Kubernetes secret name (created by SecretProviderClass)
  kubernetesSecretName: "db-credentials"

# Auto-sync configuration
syncSecret:
  enabled: true



image:
  # This will be replaced with the actual ECR URL in the deploy step
  repository: ${ECR_REPOSITORY_URL}
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: aws-ecr-secret

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: ""  # No domain required
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

# Application configuration
app:
  secretName: db-credentials  # Single reference to the secret created by SecretProviderClass
  
# Environment variables
env:
  database:
    host: "eks-postgres.cyjm8aommiol.us-east-1.rds.amazonaws.com"
    port: "5432"
    name: "app_database"
  redis:
    host: "eks-redis.nlt4fi.0001.use1.cache.amazonaws.com"
    port: "6379"
  
