replicaCount: 1

image:
  repository: nginx  # Using nginx as a sample application
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: ""  # No domain required
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

# Environment variables will be populated from Terraform outputs
env:
  - name: DB_HOST
    value: "eks-postgres.cyjm8aommiol.us-east-1.rds.amazonaws.com:5432"  # Will be replaced by the deploy script
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "app_database"
  - name: DB_USER
    value: "app_user"
  - name: DB_PASSWORD
    value: "app_password"  # In production, use Kubernetes secrets
  # Redis cache configuration
  - name: REDIS_HOST
    value: "eks-redis.nlt4fi.0001.use1.cache.amazonaws.com"  # Will be replaced when deploying
  - name: REDIS_PORT
    value: "6379"