replicaCount: 1

# Dependencies
secretStore:
  enabled: true

postgresql:
  enabled: true
  auth:
    username: app_user
    password: app_password
    database: app_database

# CSI Secrets Store Driver
secrets-store-csi-driver:
  syncSecret:
    enabled: true
  enableSecretRotation: true

# Database configuration
database:
  host: "postgres-postgresql"
  port: "5432"
  name: "app_database"

# AWS configuration
aws:
  accountId: "" # Will be set by pipeline
  region: us-east-1

# Auto-sync configuration
syncSecret:
  enabled: true



image:
  # This will be replaced with the actual ECR URL in the deploy step
  repository: ${ECR_REPOSITORY_URL}
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: aws-ecr-secret

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

ingress:
  enabled: true
  ingressClassName: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: ""  # No domain required
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

# Environment variables will be populated from Terraform outputs
env:
  - name: DB_HOST
    value: "eks-postgres.cyjm8aommiol.us-east-1.rds.amazonaws.com:5432"  # Will be replaced by the deploy script
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "app_database"
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: password
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: username
  - name: ENVIRONMENT
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: ENVIRONMENT
  # Redis cache configuration
  - name: REDIS_HOST
    value: "eks-redis.nlt4fi.0001.use1.cache.amazonaws.com"  # Will be replaced when deploying
  - name: REDIS_PORT
    value: "6379"# Trigger deployment with fixed IAM
  
