apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "myapp/db-credentials-v2"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db-username"
          - path: "password"
            objectAlias: "db-password"
          - path: "Application_Port"
            objectAlias: "application-port"
          - path: "API_KEY"
            objectAlias: "api-key"
  secretObjects:
  - secretName: db-credentials
    type: Opaque
    data:
    - objectName: db-username
      key: username
    - objectName: db-password
      key: password
    - objectName: application-port
      key: Application_Port
    - objectName: api-key
      key: API_KEY