replicaCount: 1

image:
  repository: ${ACR_LOGIN_SERVER}/myapp
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

ingress:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 50m
    memory: 64Mi

env:
  - name: DB_HOST
    value: "myapp-postgres-flex.postgres.database.azure.com"
  - name: DB_PORT
    value: "5432"
  - name: DB_NAME
    value: "app_database"
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: password
  - name: REDIS_HOST
    value: "myapp-redis-2024.redis.cache.windows.net"
  - name: REDIS_PORT
    value: "6379"