name: EKS Deployment Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ secret-sync ]
    paths:
      - 'eks/app/**'
      - 'eks/helm-charts/**'

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: my-eks-cluster

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REPOSITORY_URL="${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/myapp"
          
          docker build -t $ECR_REPOSITORY_URL:latest ./eks/app
          docker push $ECR_REPOSITORY_URL:latest

  deploy-kubernetes:
    name: Deploy to Kubernetes
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.8.0'

      - name: Configure kubectl
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Setup Cluster Access
        run: |
          # Create ECR pull secret
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          kubectl create secret docker-registry aws-ecr-secret \
            --docker-server=${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com \
            --docker-username=AWS \
            --docker-password=$(aws ecr get-login-password --region us-east-1) \
            --namespace=default \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy Application
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REPOSITORY_URL="${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/myapp"
          
          helm dependency update ./eks/helm-charts/application
          
          helm upgrade --install myapp ./eks/helm-charts/application \
            --set image.repository=$ECR_REPOSITORY_URL \
            --set image.tag=latest \
            --set aws.accountId=$ACCOUNT_ID \
            --wait --timeout=5m